- requests_kerberos/kerberos_.py
cloudera/hue developers were seeing a large number of log errors for
200 status code responses. Instead of slowly growing a list of status codes
to not log an error message for, let's just not log the message if the response
code is "ok" (`200 <= status_code < 400`, vaguely speaking).
> Stop logging on otherwise acceptable responses

- requests_kerberos/kerberos_.py
- test_requests_kerberos.py
I found that requests-kerberos recurses until it blows the stack in the case where:
1. Server responds with 401 Unauthorized.
2. requests-kerberos retries the request with an Authorization header.
3. Server responds with 401 again, because the authenticated user has not been granted access.
This pull request changes the behaviour such that the response to `handle_401()` is returned with no further processing.
Tested with SharePoint Server 2013.
> Prevent infinite recursion when server responds with 401 to an authentication attempt.

- .travis.yml
- requests_kerberos/kerberos_.py
- requirements.txt
- setup.py
Add kerberos-sspi as an alternative backend.
[kerberos-sspi](https://github.com/may-day/kerberos-sspi) package is an API level equivalent with kerberos
package but uses windows sspi (through pywin32)
> Add Windows native authentication support

- setup.py
- test_requests_kerberos.py
This is an attempt to fix #51.
It was done and validated on Windows aith Python 3.4 installed through anaconda.
I lack experience in compatibility issue between python 2 and python 3 : your guidance in how to reach an acceptable patch is more then welcome :-)
> Uses kerberos_sspi on windows

- requirements.txt
- setup.py
This change fixes the dependency issue in the whl. Now the metadata.json in the whl looks like:
```json
"run_requires": [
{"environment": "sys_platform==\"win32\"", "requires": ["kerberos-sspi (>=0.2)"]}, 
{"environment": "sys_platform!=\"win32\"", "requires": ["pykerberos (>=1.1.1,<2.0.0)"]}, 
{"requires": ["requests (>=1.1.0)"]}
]
```
For PY3 support, I took the liberty of changing the *nix dependency to use `pykerberos` instead of `kerberos`, but I'm not able to test against a real Kerberos-authenticating server on *nix. I fixed the version based on the discussion in #38.
I set kerberos-sspi to >= 0.2 because 0.2 is the one that claims PY3 support, and based on the discussion in #34. It's also the only version that I've been using. In the highly unlikely (AFAIK) event that someone on …
> Fix dependency for kerberos-sspi on Windows; else use pykerberos. (Fixes #51, #38)

- README.rst
- requests_kerberos/exceptions.py
- requests_kerberos/kerberos_.py
- test_requests_kerberos.py
Fixes #68.
Existing code doesn't work with Windows Negotiate if mutual_auth is REQUIRED, since current code stops sending Authorization headers after success, but Windows keeps a persistent connection and stops sending WWW-Authenticate responses. This change allows Kerberos auth to be forced on each request by setting force_preemptive=True (defaults to False). 
Also "accidentally" fixes #65, since we needed a way to preemptively auth on every request anyway.
Updated existing tests to pass with changed internal args, but haven't added tests for new functionality yet. This is obviously "work in progress"- if the approach is sound, I'll add tests and clean up other things.
> Fix for mutual auth on winrm

- README.rst
- requests_kerberos/kerberos_.py
- test_requests_kerberos.py
Requests-kerberos currently only supports the default principal (ie, whoever the last user you ran kinit/switch for). pykerberos *mostly* supports principal override (it's been broken for awhile, but I'm working on fixing it)- this allows for collection credential caches (like dir and API) to be searched for a matching principal name, and the use of the tickets/TGT contained within. This is a really important feature for Ansible, as we need the ability to support multiple principals simultaneously (kswitch can't do that).
This PR also adds hostname override, a feature that pywinrm needs for parity with its old urllib2-based version. This decouples the hostname in the URL from the kerberos exchange, allowing a host to be accessed via an arbitrary URL hostname (eg for cases of name-based …
> add support for principal and realm override

- README.rst
- requests_kerberos/kerberos_.py
- test_requests_kerberos.py
Mutual auth error sanitization breaks WinRM long-running operation poll timeout, since it's returned as a 500 without a WWW-Authenticate header. We need a way to allow returning the full error response, as this isn't *really* an error, but we have to see the response to know for sure.
added test coverage, doc update
> make mutual auth error sanitization optional

- README.rst
- requests_kerberos/kerberos_.py
- test_requests_kerberos.py
The goal here is to avoid passing the `principal` keyword argument that's unrecognized by kerberos-sspi, while gracefully failing if someone tries to use it with kerberos-sspi / Windows.
This is a holdover until I get around to trying out WinKerberos as the successor to kerberos-sspi + pywin32.
> Block use of `principal` argument when using kerberos-sspi. Fixes #71.

- README.rst
- requests_kerberos/kerberos_.py
- requirements.txt
- setup.py
- test_requests_kerberos.py
This reverts the temporary workarounds in #73, and swaps the use of kerberos-sspi with WinKerberos. It's not ready to merge, but looks promising.
@behackett The unit tests fail because WinKerberos doesn't define GSSError, a subclass of KrbError.
> Replace kerberos-sspi with WinKerberos. Fixes #67.

- requirements-test.txt
Need to set an upper limit for pytest so we can continue to test with Python 3.3. This should be revisited sometime in the future.
> added pytest restriction for Python 3.3 compatibility

- setup.py
Now PYPI should be able to recognise license.
Fixes #122
> Added missing trove classifier for license

- requests_kerberos/kerberos_.py
- tests/test_requests_kerberos.py
When used from different threads (or potentially as part of an event loop), it is possible that two different requests to the same host occurring concurrently could stomp on one anothers kerberos context in the context dictionary. This could result in client or server (mutual) authentication failures as the wrong context would be used at different times.
To resolve this, we do two things:
1. Within a call to `generate_request_header`, we bind the context we generate to a name local to the function, and always use the context via that name. As a result, any concurrently executing call to `generate_request_header` will be unable to rebind a new context to that name.
2. When populating the context dictionary, we index by  `PreparedRequest` object instead of request urls `hostname`. This is …
> Resolve potential concurrency issue

- requests_kerberos/kerberos_.py
Mark the regex as a raw string instead.
Also-authored-by: Stanislav Levin <slev@altlinux.org>
See: https://github.com/pythongssapi/requests-gssapi/pull/10 and https://github.com/pythongssapi/requests-gssapi/issues/9
> Fix invalid escape sequence "\s"

- HISTORY.rst
- requests_kerberos/kerberos_.py
Updates the regex pattern to avoid a DoS attack against the client trying to perpetually scan the header. This is the same change that `requests-gssapi` has implemented without any side affects so far https://github.com/pythongssapi/requests-gssapi/pull/22.
Fixes https://github.com/requests/requests-kerberos/issues/145
Fixes https://github.com/requests/requests-kerberos/issues/152
> Fix negotiate regex patter

- HISTORY.rst
- requests_kerberos/__init__.py
- requests_kerberos/kerberos_.py
The raw Kerberos token from the server was being used in the debug logs which can be problematic when dealing with invalid codepoints. This PR makes sure we log the base64 value which will always contain just ASCII chars.
Also adds the changelog entry for https://github.com/requests/requests-kerberos/pull/149.
Fixes https://github.com/requests/requests-kerberos/issues/168
> Fix stray byte conversion and added changelog

- HISTORY.rst
- README.rst
It was pointed out that `send_cbt` is not documented and the addition of automatic channel binding data was  not mentioned in the changelog. This PR expands the docs to further talk about this process and how it can be disabled in the case the server does not support this.
Fixes https://github.com/requests/requests-kerberos/issues/173
> Add more docs on send_cbt

- requests_kerberos/kerberos_.py
Previously, once you successfully generated channel binding data for one host, it would be stored in self.cbt_struct, and self.cbt_binding_tried would be set to True, preventing ever recalculating self.cbt_struct. This means that once you used an HTTPKerberosAuth object to talk to one host, it would keep sending that channel binding data to other hosts, resulting in failures for servers that enforce channel binding.
Instead, store CBTs in a per-host dictionary as we do with GSSAPI contexts.
> Make channel binding data per-host

- .gitignore
- requests_kerberos/kerberos_.py
- tests/test_requests_kerberos.py
Hi,
This pull request is for parsing the principal if it is given in the form of user@REALM:password. It will split the username and password and pass them both to spnego.client().
> fix #181 add password param to constructor

- HISTORY.rst
- README.rst
- requests_kerberos/__init__.py
Bumps the version to `0.15.0` and updates the README to cover system dependencies and the new `password` argument.
Fixes: https://github.com/requests/requests-kerberos/issues/175
> Update readme and prepare for v0.15.0 release

- .github/workflows/ci.yml
Also updates the CI action versions to use the non-deprecated node version.
> Update CI to include Python 3.11, 3.12
